### PR TITLE
Update jekyll-org for Jekyll v3

### PR DESCRIPTION
**Pull request by parkr**
@bzg was looking for this here: https://talk.jekyllrb.com/t/would-the-maintainers-be-open-for-a-pr-adding-org-support/2210/4

/cc @eggcaker

### CODE REVIEW

**Comment by bzg** [comment]
That's great, thanks @parkr.

**Comment by bzg** [comment]
I've tested the patch and it's working fine for `jekyll 3.1.2` (which I think is the latest stable.)

FWIW it throws this error with `jekyll 3.0.2`:

> Error converting file _posts/2013-05-26-bastien_guerry_orgmode_emacs_chat.org: undefined method `merged_file_read_opts' for Jekyll::Utils:Module ["/home/guerry
/install/git/emacsdoctor/_plugins/jekyll-org/convert.rb:45:in `read'", "/var/lib/gems/2.1.0/gems/jekyll-3.0.2/lib/jekyll/readers/post_reader.rb:36:in `each'", 
"/var/lib/gems/2.1.0/gems/jekyll-3.0.2/lib/jekyll/readers/post_reader.rb:36:in `block in read_publishable'"

Maybe not important, I don't know if many people use `jekyll < 3.1".

Thanks again!

**Comment by stig** [comment]
It seems to work great with YAML front-matter, but I can't seem to get the promised org-style alternative to work, e.g.

```org
#+TITLE: foo
#+LAYOUT: post
#+TAGS: Foo Bar
```

**Comment by eggcaker** [comment]
just test it's working with the org-style meta data configuration ex: 
```
#+LAYOUT: post
#+TITLE:  "Welcome to Jekyll with orgmode !"
#+TAGS: Hello, Category
#+DATE: 2016-04-01
```

**NOTES: ** you can not insert `#CATEGORIES: some-cate` in the header.

**Comment by stig** [comment]
Ah! It *does* work for blog posts in the _post directory, but not for
regular pages... Well, that's a good start for me :-)

**Comment by eggcaker** [comment]
@stig yes, it's not support at this project started. I think people doesn't  really need write lot of page with org-mode in jekyll(maybe i'm totally wrong)

**Comment by bzg** [comment]
@eggcaker well, we certainly _hope_ more and more people will need to write org-mode files with Jekyll :-)  Thanks for the fix again.

**Comment by stig** [comment]
> I think people doesn't really need write lot of page with org-mode in
> jekyll(maybe i'm totally wrong)

People probably don't _need_ to but I would love to do so :-)

**Comment by eggcaker** [comment]
it's true

**Pull request merged**
